#spring.datasource.url=jdbc:mysql://localhost:3306/blogDB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
#spring.datasource.username=root
#spring.datasource.password=ehgns8418
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blogDB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: ehgns8418

  thymeleaf:
    cache: false
#  spring.thymeleaf.cache : Thymeleaf ?? ???? ??? ?? ?????? ??? ??
#  ???? ?? ?????. ?, ??? ? false? ?? ??? ???? ??, ????? true?
#  ???? ???.

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      use-new-id-generate-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

server:
  port: 8084